# Generated by Django 3.2.9 on 2022-02-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=50, unique=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Anno_Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos_cursados', to='administrar.anno', verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'ordering': ('-curso',),
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_horas_plan', models.IntegerField(verbose_name='Horas por Plan')),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asiganturas', to='administrar.anno', verbose_name='Año')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_plan', to='administrar.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50, unique=True, verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría Científica',
                'verbose_name_plural': 'Categorías Científicas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Categoria_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría Docente',
                'verbose_name_plural': 'Categorías Docentes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50, unique=True, verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('curso',),
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10, verbose_name='Grupo')),
                ('anno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', related_query_name='grupo', to='administrar.anno_cursado', verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Responsabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('peso', models.IntegerField(verbose_name='Peso de Responsabilidad')),
            ],
            options={
                'verbose_name': 'Responsabilidad',
                'verbose_name_plural': 'Responsabilidades',
                'ordering': ('peso',),
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo')], max_length=20)),
            ],
            options={
                'ordering': ('semestre',),
            },
        ),
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Cursos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ('titulo',),
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('nombre', 'apellido'), 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('nombre', 'apellido', 'email')},
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgrupo', models.CharField(max_length=10, verbose_name='Subgrupo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='administrar.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre_Cursado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='administrar.curso')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.semestre')),
            ],
            options={
                'ordering': ('curso',),
            },
        ),
        migrations.CreateModel(
            name='ProfesorPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrar.users')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('movil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Móvil')),
                ('categoria_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='administrar.categoria_docente', verbose_name='Categoría Docente')),
                ('categorias_cientficas', models.ManyToManyField(related_name='profesores_cat_cientifica', to='administrar.Categoria_Cientifica')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='administrar.titulo')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='ProfesorAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_conferencias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Conferencia')),
                ('cant_grupos_conferencias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Conferencia')),
                ('horas_cp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica')),
                ('cant_grupos_cp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Clase Practica')),
                ('horas_cpc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica Computadoras')),
                ('cant_grupos_cpc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Clase Practica Computadoras')),
                ('horas_lab', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Laboratorio')),
                ('cant_grupos_lab', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Laboratorio')),
                ('horas_taller', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Taller')),
                ('cant_grupos_taller', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Taller')),
                ('horas_seminarios', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Seminario')),
                ('cant_grupos_seminario', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad Grupos Seminario')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impartidas', related_query_name='impartida', to='administrar.asignatura_plan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docencias_created', to='administrar.users')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impartidas', to='administrar.semestre_cursado', verbose_name='Curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impartidas', related_query_name='impartida', to='administrar.profesorperfil')),
            ],
        ),
        migrations.CreateModel(
            name='Profe_Responsabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', related_query_name='funcion', to='administrar.users', verbose_name='Profesor Responsable')),
                ('responsabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.responsabilidades')),
            ],
            options={
                'ordering': ('responsabilidad',),
            },
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('curso_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='administrar.curso', verbose_name='Curso de Comienzo')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='administrar.profe_responsabilidades', verbose_name='Profesor Guía'),
        ),
        migrations.CreateModel(
            name='EstudiantePerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiantes', serialize=False, to='administrar.users')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='administrar.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('jefe_disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', related_query_name='disciplina', to='administrar.profe_responsabilidades', verbose_name='Jefe de Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrera_coordinador', to='administrar.profe_responsabilidades', verbose_name='Coordinador de Carrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='jefe_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrera_jefedepartamento', to='administrar.profe_responsabilidades', verbose_name='Jefe de Departamento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='segundo_jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrera_segundo_jefe', to='administrar.profe_responsabilidades', verbose_name='Segundo Jefe de Departamento'),
        ),
        migrations.AddField(
            model_name='asignatura_plan',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', related_query_name='asignatura', to='administrar.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='asignatura_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_plan', to='administrar.plan_estudio'),
        ),
        migrations.AddField(
            model_name='asignatura_plan',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrar.semestre'),
        ),
        migrations.AddField(
            model_name='asignatura_plan',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='administrar.tipo_curso', verbose_name='Tipo de Curso'),
        ),
        migrations.AddField(
            model_name='anno_cursado',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='administrar.carrera'),
        ),
        migrations.AddField(
            model_name='anno_cursado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='administrar.curso'),
        ),
        migrations.AddField(
            model_name='anno_cursado',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='administrar.plan_estudio', verbose_name='Plan de Estudio'),
        ),
        migrations.AddField(
            model_name='anno_cursado',
            name='principal_anno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annos_ppa', to='administrar.profe_responsabilidades', verbose_name='Profesor Principal de Año'),
        ),
        migrations.AddField(
            model_name='anno_cursado',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annos', to='administrar.tipo_curso', verbose_name='Tipo de Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='anno_cursado',
            unique_together={('anno', 'carrera', 'curso', 'plan', 'tipo_curso')},
        ),
    ]
